# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'keyboardTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for keyboardTest
  pod 'IQKeyboardManagerSwift'
  target 'keyboardTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'keyboardTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
